import Head from "next/head";
import { Card, Image } from "antd";
import { GetSessionParams, getSession, signIn } from "next-auth/react";
import { AppleOutlined, FacebookOutlined, GithubOutlined, GoogleOutlined, TwitterOutlined } from "@ant-design/icons";
import { ReactElement } from "react";

const { Meta } = Card;

const Index = (): JSX.Element => {
  // const router: NextRouter = useRouter();
  // const { data, status }: Session = useSession();

  // useEffect(() => {
  //   if (status === "unauthenticated" && router?.pathname !== "/login") {
  //     router?.push("/");
  //   }
  // }, [router, status]);

  return (
    <>
      <Head>
        <title>Template NextJs - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="login">
        <Card
          hoverable
          cover={<Image src="https://picsum.photos/200/300" alt="logo" preview={false} />}
          actions={[
            <GoogleOutlined key="google" onClick={() => signIn("google")} />,
            <AppleOutlined key="apple" />,
            <TwitterOutlined key="twitter" />,
            <GithubOutlined key="github" onClick={() => signIn("github")} />,
            <FacebookOutlined key="facebook" />,
          ]}
        >
          <Meta
            // avatar={<Avatar src="https://xsgames.co/randomusers/avatar.php?g=pixel" />}
            title="Bienvenido al template de NextJs"
            description="Inicia sesión con el proveedor de tu preferencia"
          />
        </Card>
      </div>
    </>
  );
};

Index.getLayout = (page: ReactElement) => page;

export const getServerSideProps = async (context: GetSessionParams | undefined) => {
  const session = await getSession(context);

  if (session)
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };

  return {
    props: {
      session,
    },
  };
};

export default Index;
